"""
Export a bricks payload to LDraw .ldr format.

LDraw conventions:
  - Right-handed: +X right, +Y down (inverted), +Z toward viewer
  - 1 stud horizontal = 20 LDU
  - 1 brick height    = 24 LDU
  - 1 plate height    = 8 LDU
  - Part origin is at the CENTER of the bottom face

Each line format for placed parts:
    1 <color> <x> <y> <z> <a b c d e f g h i> <part>.dat

The matrix (a..i) is row-major 3x3. We use:
  - identity for "natural" orientation (long axis along Z)
  - Y-90° for footprints where size_x > size_y
  - Y-rotation for slopes so the low end faces the requested direction
"""

from __future__ import annotations

from brick_catalog import BRICK_LDU, CATALOG, PLATE_LDU, STUD_LDU


# Identity and standard rotations about Y axis (row-major 3x3)
ROT_NONE = "1 0 0 0 1 0 0 0 1"
ROT_Y90  = "0 0 1 0 1 0 -1 0 0"
ROT_Y180 = "-1 0 0 0 1 0 0 0 -1"
ROT_Y270 = "0 0 -1 0 1 0 1 0 0"

# For slope direction: which Y rotation makes the slope's low end face the
# requested world direction. The base LDraw slope (e.g. 3037) has its low
# end facing +X by convention (sloping down toward +X).
SLOPE_ROT = {
    "+x": ROT_NONE,
    "-y": ROT_Y90,
    "-x": ROT_Y180,
    "+y": ROT_Y270,
}


def _palette_color_id(palette: list[dict], color_id: int) -> int:
    for p in palette:
        if p["id"] == color_id:
            return int(p.get("ldraw", 16))
    return 16


def to_ldraw(payload: dict, model_name: str = "Generated by lego-ai") -> str:
    palette = payload.get("palette", [])
    bricks = payload.get("bricks", [])

    # If there's a baseplate (z=-1), the whole model is shifted UP by 1 plate
    # height (8 LDU) so the baseplate sits at LDraw Y=0.
    has_baseplate = any(b.get("z") == -1 for b in bricks)
    y_offset = -PLATE_LDU if has_baseplate else 0

    lines: list[str] = [
        f"0 {model_name}",
        f"0 Name: model.ldr",
        f"0 Author: lego-ai",
        f"0 !LDRAW_ORG Unofficial_Model",
        f"0 BFC CERTIFY CCW",
    ]

    for b in bricks:
        cat = _lookup_brick(b)
        if cat is None:
            continue
        ldraw_color = _palette_color_id(palette, b["color"])
        x_ldu, y_ldu, z_ldu, rot = _placement(b, cat, y_offset)
        part = cat["ldraw"]
        lines.append(
            f"1 {ldraw_color} {x_ldu} {y_ldu} {z_ldu} {rot} {part}.dat"
        )

    return "\n".join(lines) + "\n"


def _lookup_brick(b: dict) -> dict | None:
    kind = b.get("kind", "brick")
    bt   = b.get("brick_type")
    return CATALOG.get((kind, bt))


def _placement(b: dict, cat: dict, y_offset: int) -> tuple[int, int, int, str]:
    vx, vy, vz = int(b["x"]), int(b["y"]), int(b["z"])
    sx, sy = int(b["size_x"]), int(b["size_y"])
    kind = b.get("kind", "brick")

    # Horizontal: footprint center
    x_ldu = vx * STUD_LDU + (sx * STUD_LDU) // 2
    z_ldu = vy * STUD_LDU + (sy * STUD_LDU) // 2

    # Vertical: each voxel layer = 1 brick height = 24 LDU.
    # The piece's bottom-face origin sits at the bottom of its voxel slot.
    # LDraw Y goes DOWN, so origin_y = -voxel_z * BRICK_LDU.
    # Baseplate at z=-1 sits with bottom at y = +PLATE_LDU (one plate below 0).
    if vz < 0:
        # Baseplate: lives at z=-1, top should be at y=0, so its origin (bottom
        # face) is at y = +PLATE_LDU. We translate up by y_offset already so the
        # rest sits correctly.
        y_ldu = PLATE_LDU
    else:
        y_ldu = -vz * BRICK_LDU + y_offset

    # Rotation
    if kind in ("slope", "slope_inv"):
        direction = b.get("slope_dir") or "+x"
        rot = SLOPE_ROT.get(direction, ROT_NONE)
    else:
        # Standard bricks/plates/tiles use the size-based rule from before
        rot = ROT_Y90 if sx > sy else ROT_NONE

    return x_ldu, y_ldu, z_ldu, rot
