"""
Export a bricks payload to Wavefront OBJ (+ MTL).

Each brick becomes a unit cube. Tiles/plates are 1/3 height. Slopes carve
their cube with a diagonal cut. Bricks of the same color share a material.
"""

from __future__ import annotations

import io
from collections import defaultdict

from brick_catalog import BRICK_LDU, PLATE_LDU, STUD_LDU


CUBE_VERTS = [
    (0, 0, 0), (1, 0, 0), (1, 1, 0), (0, 1, 0),
    (0, 0, 1), (1, 0, 1), (1, 1, 1), (0, 1, 1),
]
CUBE_FACES = [
    (1, 2, 3), (1, 3, 4),
    (5, 8, 7), (5, 7, 6),
    (1, 5, 6), (1, 6, 2),
    (2, 6, 7), (2, 7, 3),
    (3, 7, 8), (3, 8, 4),
    (4, 8, 5), (4, 5, 1),
]


def _height_units(kind: str) -> float:
    """Brick = 1.0, plate/tile = 1/3."""
    if kind in ("plate", "tile"):
        return PLATE_LDU / BRICK_LDU
    return 1.0


def _y_offset_for_z(z: int, has_baseplate: bool) -> float:
    """LDraw-equivalent Y offset for the bottom of a piece at voxel layer z."""
    base = z if z >= 0 else 0  # baseplate (z=-1) handled separately
    return base * 1.0 + (PLATE_LDU / BRICK_LDU if has_baseplate and z >= 0 else 0)


def to_obj(payload: dict, mtl_filename: str = "model.mtl") -> tuple[str, str]:
    bricks = payload.get("bricks", [])
    palette = {p["id"]: p for p in payload.get("palette", [])}
    has_baseplate = any(b.get("z", 0) == -1 for b in bricks)

    obj = io.StringIO()
    obj.write(f"# Generated by lego-ai — {len(bricks)} pieces\n")
    obj.write(f"mtllib {mtl_filename}\n")

    by_color: dict[int, list[dict]] = defaultdict(list)
    for b in bricks:
        by_color[b["color"]].append(b)

    v_offset = 0
    for color_id, group in by_color.items():
        mat = f"color_{color_id}"
        obj.write(f"\no {mat}\n")
        obj.write(f"usemtl {mat}\n")
        for b in group:
            kind = b.get("kind", "brick")
            height = _height_units(kind)
            base_y = (
                -PLATE_LDU / BRICK_LDU if b["z"] == -1
                else _y_offset_for_z(b["z"], has_baseplate)
            )
            for (dx, dy, dz) in CUBE_VERTS:
                x = (b["x"] + b["size_x"] * dx)
                zc = (b["y"] + b["size_y"] * dy)
                y_voxel = base_y + height * dz
                # Multiply Y by brick aspect ratio for visual realism (1.2x stud width)
                obj.write(f"v {x:.4f} {y_voxel * 1.2:.4f} {zc:.4f}\n")
            for (a, c, d) in CUBE_FACES:
                obj.write(f"f {a + v_offset} {c + v_offset} {d + v_offset}\n")
            v_offset += len(CUBE_VERTS)

    mtl = io.StringIO()
    mtl.write(f"# Materials for lego-ai export\n")
    for color_id in by_color:
        pal = palette.get(color_id, {})
        rgb = pal.get("rgb", [180, 180, 180])
        r, g, bcomp = [v / 255 for v in rgb]
        mtl.write(f"newmtl color_{color_id}\n")
        mtl.write(f"Kd {r:.4f} {g:.4f} {bcomp:.4f}\n")
        mtl.write(f"Ka 0 0 0\n")
        mtl.write(f"Ks 0.1 0.1 0.1\n")
        mtl.write(f"d 1\n")
        mtl.write(f"illum 2\n\n")

    return obj.getvalue(), mtl.getvalue()
